// Code generated by entc, DO NOT EDIT.

package account

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// EdgeMailboxes holds the string denoting the mailboxes edge name in mutations.
	EdgeMailboxes = "mailboxes"
	// Table holds the table name of the account in the database.
	Table = "accounts"
	// MailboxesTable is the table that holds the mailboxes relation/edge.
	MailboxesTable = "mailboxes"
	// MailboxesInverseTable is the table name for the Mailbox entity.
	// It exists in this package in order to avoid circular dependency with the "mailbox" package.
	MailboxesInverseTable = "mailboxes"
	// MailboxesColumn is the table column denoting the mailboxes relation/edge.
	MailboxesColumn = "account_mailboxes"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldUUID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
