// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Mailbox is the predicate function for mailbox builders.
type Mailbox func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)
